### ISSUE TITLE
Compiler work metabug

### ISSUE THREAD

**Issue by S11001001** [ermine-language/ermine#24]
From @pchiusano, @dolio, @joshcough, 7 April 2014. (cc @ekmett)

* [x] wrap up minor stuff with current pattern compiler
* [x] implement guards
* [x] Implement some machinery that makes the pattern compiler easier to call.
* [x] End-to-end compile for some simple lambda terms.
* [ ] Determine internal representation for instances
* [ ] Parsing instances
* [ ] Doing something useful with parsed instances
* [x] Type checking with patterns and instances, and other missing cases in the typechecker
* [ ] Determine module representation and tweak Core representation (including platform blocks)
* [ ] Write module parser
* [ ] Module serialization
* [ ] Row types
* [ ] Core library
* [ ] Core interpreter, fully fleshed out in Scala
* [ ] Better documentation
